- resources/assets/js/views/Preview.vue
- resources/assets/sass/views/_preview.scss
reopened this branch to merge, because I added a new smaller button
> delete button size fixes

- app/Validation/Brokers/DefinitionBroker.php
- there was a bug where non required fields with max-length etc wouldn't validate if they were empty
> fixed max-length validation bug

- resources/assets/js/components/icons.js
- resources/assets/js/components/sidebar/Toolbar.vue
- resources/assets/sass/views/_editor.scss
@sy238-unikent will open /draft/{{pageId}} in a new tab
> added preview button

- resources/assets/js/components/CreatePageModal.vue
altered the hardcoded layout name options when you create a new page
> changed layout names and defaults

- resources/assets/js/store/modules/site.js
- resources/assets/js/views/Editor.vue
see #57 - this is a cleaned up version of that...
> Fixes so editor loads correct sites page hierarchy.

- app/Http/Controllers/Api/v1/PublishingGroupController.php
- app/Http/Transformers/Api/v1/PublishingGroupTransformer.php
- app/Http/Transformers/Api/v1/UserTransformer.php
- app/Policies/PublishingGroupPolicy.php
- app/Providers/AuthServiceProvider.php
- routes/api.php
- tests/Unit/Policies/PublishingGroupPolicyTest.php
Relevant API documentation:
https://unikent.github.io/astrodocs/api.html#list-publishing-groups
https://unikent.github.io/astrodocs/api.html#publishing-group
> Add retrieval of publishing groups with optional lists of sites and users to the API. Needs tests.

- app/Models/APICommands/CreateSite.php
- app/Models/Page.php
- app/Models/Site.php
- app/Models/User.php
- tests/Unit/Models/APICommands/CreateSiteTest.php
A few additions to the unit tests for creating a site.
> Improve unit tests for CreateSite.

- resources/assets/js/plugins/key-commands.js
haven't removed all undo/redo code, just the command key controls
> removed key commands for undo/redo

- app/Http/Controllers/Api/v1/PageController.php
- app/Models/APICommands/UpdatePage.php
- app/Models/APICommands/UpdatePageSlug.php
- app/Models/LocalAPIClient.php
- app/Providers/AppServiceProvider.php
- resources/assets/js/components/sidebar/index.vue
- routes/api.php
> Add command to change page slug

- resources/assets/js/components/Block.vue
- resources/assets/js/components/sidebar/Errors.vue
- resources/assets/js/views/Editor.vue
- added jump links so users can jump to the error block
- hid valid blocks from the error sidebar
> added jump links for block errors

- resources/assets/js/components/PublishModal.vue
- appropriate fail message if user has no internet connection
- improved general error display
- added fullscreen publishing message
> improved network connection check on publish

- app/Models/Permission.php
- app/Models/Role.php
- composer.json
- composer.lock
- database/migrations/2017_10_11_105646_create_permissions_tables.php
See https://trello.com/c/X8HkgZzX/282-create-database-migrations-and-models-for-permissions
> Create migration and models for permissions

- app/Models/LocalAPIClient.php
- app/Models/Page.php
required for compatibility with https://github.com/unikent/astro-renderer/pull/11 (but will break preview mode without it)
> Minor change for compatibility with renderer.

- app/Http/Controllers/Api/v1/SiteController.php
- app/Http/Controllers/Api/v1/UserController.php
- app/Http/Transformers/Api/v1/RoleTransformer.php
- app/Http/Transformers/Api/v1/SiteTransformer.php
- app/Http/Transformers/Api/v1/SiteUserTransformer.php
- app/Http/Transformers/Api/v1/UserRoleTransformer.php
- app/Http/Transformers/Api/v1/UserTransformer.php
- app/Models/Permission.php
- app/Models/Site.php
- app/Models/User.php
- app/Models/UserSiteRole.php
- app/Policies/PermissionPolicy.php
- app/Policies/UserPolicy.php
- app/Providers/AuthServiceProvider.php
- routes/api.php
- tests/Support/Astro.postman_collection.json
Retrieval of users, including their roles / sites
Optionally include currently authenticated user's role on each site in site requests.
Optionally include each user-role combination for each site in site requests.
> API improvements for permissions

- app/Console/Commands/SetupPermissions.php
- app/Http/Controllers/Api/v1/SiteController.php
- app/Http/Controllers/Api/v1/UserController.php
- app/Http/Transformers/Api/v1/PermissionTransformer.php
- app/Http/Transformers/Api/v1/RoleTransformer.php
- app/Http/Transformers/Api/v1/SiteUserTransformer.php
- app/Http/Transformers/Api/v1/UserRoleTransformer.php
- app/Http/Transformers/Api/v1/UserTransformer.php
- app/Models/APICommands/UpdateSiteUserRole.php
- app/Models/LocalAPIClient.php
- app/Models/Permission.php
- app/Models/Role.php
- app/Models/UserSiteRole.php
- app/Policies/RolePolicy.php
- app/Providers/AuthServiceProvider.php
- database/migrations/2017_10_19_114913_add_slug_to_roles.php
- database/migrations/2017_10_19_114923_add_slug_to_permissions.php
- routes/api.php
- tests/Support/Astro.postman_collection.json
API specification has also been updated to match this: https://unikent.github.io/astrodocs/api.html#assign-remove-a-user-to-a-site
Apologies for mixing the changes with a bunch of spaces -> tabs fixes.
PUT /api/v1/sites/{site_id}/users with json body of:
{
"username": "user to be updated's username",
"role": "name of the role to assign to the user for this site."
}
Leave "role" null, empty or don't include it at all to remove the user from that site.
> Add UpdateSiteUserRole to set (or remove) the role for a user on a site via API.

- app/Console/Commands/SetupPermissions.php
- app/Http/Controllers/Api/v1/SiteController.php
- app/Models/Permission.php
- app/Policies/SitePolicy.php
and check for this AND edit site depending on what options are updated in the API call.
REMEMBER TO php artisan astro:permissions refresh
> Add permission for editing site options 

- database/migrations/2017_11_08_131533_add-sections-to-blocks.php
- database/migrations/2017_11_08_132752_add-sections-to-revision_blocks.php
might be worth taking a sql dump or your database before testing this in case need to revert...
also note am asking to merge into new epic/templates branch
> Add sections to blocks and update baked block data in revisions.

- resources/assets/js/views/SiteList.vue
> Revert "Comment out delete site button since its not yet implemented"

- resources/assets/js/components/CreatePageModal.vue
- resources/assets/js/components/EmptyRegion.vue
added school about us layout to the dropdown list
> added School about us layout

- app/Models/APICommands/UpdateContent.php
- resources/assets/js/store/modules/page.js
- tests/Unit/Models/APICommands/UpdateContentTest.php
This improves the validation messages generated by the API during update content and displays them to the user.
> Display page validation errors

- tests/Unit/Models/APICommands/UpdateContentTest.php
- fixed broken test
- various indentation, code formatting tidy-ups
> - Fixed failing test by adding missing version number

- resources/assets/js/components/CreatePageModal.vue
added listing page layout to school create-page layout drop down
> added school listing page layout to the dropdown list of layouts

- resources/assets/js/components/CreatePageModal.vue
- resources/assets/js/components/EmptySection.vue
- resources/assets/sass/components/_empty-region.scss
added contact us page layout to create page dropdown
> User-friendly add blocks in empty section message

- resources/assets/js/routes.js
- resources/assets/js/store/modules/site.js
- resources/assets/js/views/Admin.vue
fixes: https://github.com/unikent/astro/issues/211
Just as a note: we need to look into centralising such API calls so that they can be shared across multiple pages
> Un-hardcode editor link on admin page
