unikent/astro

- readme.md
Github are in the process of implementing a fix to render SVGs with the correct content-type, but until then this will do.
> Fix broken logo.

- resources/assets/js/components/sidebar/Toolbar.vue
For now it just accesses window.astro.base_url which is set on the initial editor load (view page source to see).
I'm not 100% sure this can always be relied on but works for now...
> Made preview button relative to editor-root so works if editor is not at domain root.

- app/Models/User.php
- resources/assets/js/components/TopBar.vue
- resources/assets/js/components/sidebar/Toolbar.vue
- resources/views/inline.blade.php
- resources/views/layouts/app.blade.php
This fixes the login issue where it redirected to a non-existent css file.
It also sorta-fixes the logout functionality - in that the logout button now posts to logout successfully...
However, as API access is authenticated using a token that never changes, using the back button appears to get the user back into a working version of the editor...
> Make login work without redirecting to css and make logout sort-of work

- database/migrations/2017_09_01_090700_add_unique_site_version_path_index_on_pages.php
Enforces at database level the condition that paths must be unique for a version of a site.
Matthew and Sam can confirm the need for this...
Could alternately have enforced this on site_id, parent_id, version and slug.
> Add unique index to stop two pages with same path existing.

- app/Policies/MediaPolicy.php
The existing MediaPolicy is broken and dissallows all non-admins from viewing media in media library or uploading new media.
This hacky hotfix just always returns true from the MediaPolicy.
> Allow all users access to all media for now.

- app/Console/Commands/AddUser.php
- app/Models/User.php
- tests/Unit/Models/UserTest.php
We do not currently have a ui for managing users and publishing groups.
For UAT we need admins to be able to create sites for users that only those users can edit.
This feature automatically creates a publishing group when a user record is created, giving it the username
of the user, and adds the user to it.
If the group already exists, the user is added to the existing group and no new group is created.
The artisan console command astro:adduser has been updated to make group name optional. If the user account
already exists and no group name is added it creates (if it does not exist) a group with the user's username
and adds them to it (so can be used to update existing user accounts on the test server).
> Automatically create a publishing group for each new user named after their username and add them to it.

- app/Http/Transformers/Api/v1/PageTransformer.php
- app/Models/APICommands/AddPage.php
- app/Models/APICommands/CreateSite.php
- app/Models/APICommands/PublishPage.php
- app/Models/APICommands/UpdateContent.php
- app/Models/APICommands/UpdatePage.php
- app/Models/Block.php
- app/Models/Page.php
- app/Models/Revision.php
- app/Providers/AppServiceProvider.php
- database/migrations/2017_09_20_112547_add_errors_to_blocks.php
- database/migrations/2017_09_20_112625_add_valid_state_to_revisions.php
This merge request:
- Ignores block-level validation errors when saving a page (but still enforces the region-block-level validation).
- Stores any block-level validation errors with the blocks themselves, in an "errors" field for each block which is included when a page and its blocks are sent as json.
- Adds a "valid" property on each revision, which is included in the json for a Page as a "valid" field.
- Enforces the rule that all blocks must be valid before PUBLISHING a page.
> Save pages even if invalid, but only publish if valid.

- tests/Support/Astro.postman_collection.json
I have exported the configuration I am currently using to test the API with Postman.
It should be possible to import them into postman to use them to test the API.
They assume that there is a user with an API token of "test".
You will also need to fiddle with the site and page ids so that they match ones available in your installation.
> Added a Postman collection for testing API with Postman.

- resources/assets/js/classes/Definition.js
It doesn't seem like Element UI handles nested validation very well (which is why I didn't take this approach initially, I'd just forgotten).
We can re-enable this once the validation is moved out of Element.
> Temporarily disable eager loading validation.

- resources/assets/js/components/PublishModal.vue
very quick tweak that hopefully makes it easier for testers by linking to the published url for pages once published.
> Minor tweak to link to test published url from PublishModal on publishing to make it easier for testers.

- app/Http/Controllers/PageController.php
- resources/assets/js/components/PublishModal.vue
- resources/assets/js/components/Toolbar.vue
- resources/assets/js/store/modules/page.js
- resources/assets/js/views/MenuEditor.vue
- routes/web.php
Draft preview url is now similar to published page preview url '/draft/{domain-name}/{path-to-page}' instead of '/draft/{id}'.
This makes it simpler to do a string replace on the beginning of URLs to map real published URLs to ones that can be displayed in preview mode.
Added a getter to (page) state to retrieve the preview and published urls for the current page in the editor.
Moved the code that handles draft and published previewing from route file to PageController.
>  Modify draft preview route so menu link and potentially other links can be modified by renderer in preview mode.

- app/Console/Commands/ManageAdmins.php
- app/Console/Kernel.php
Simple command to list, add and remove admin users. Includes basic search on prefix if initial user not found.
> Artisan command to mange admins

- resources/assets/js/components/Toolbar.vue
Before showing the publish page dialog, save the page first. see https://trello.com/c/ypoxl22o/233-save-and-publish
> Save the page before showing publish dialog

- resources/assets/sass/views/_site-users.scss
This is to simply increase the width of the 'Filter by role' drop down in the site user management page, so that the 'Filter by role' is visible.
> Increase width of 'filter by role' drop down

- app/Http/Transformers/Api/v1/PageTransformer.php
- app/Http/Transformers/Api/v1/SiteTransformer.php
- app/Models/APICommands/UpdatePageSlug.php
- app/Models/Page.php
- resources/assets/js/store/modules/page.js
Added an attribute getter on Page model to calculate the status of a page based on the state of its published version if one exists.
Currently not eager loaded due to restrictions / lack-of-understanding of eloquent relations.
Used the existing status options as defined in store/page.js and components/TopBar.vue:
- new = Not yet published
- draft = Published but modified
- published = Published and up to date
> Update API to return published "status" for pages.

- app/Console/Commands/SetupPermissions.php
- app/Http/Controllers/Api/v1/PageController.php
- app/Models/Permission.php
- app/Policies/PagePolicy.php
- database/migrations/2017_11_06_124228_refresh_permissons.php
- database/seeds/DatabaseSeeder.php
- resources/assets/js/components/PageListItem.vue
Adds a new permission "page.unpublish" and assigns it to owners and editors.
API requires this permission to unpublish a page, editor doesn't display unpublish option if this permission is not present.
Added a migration that runs the "astro:permissions refresh" command as I kept on forgetting to do this after refreshing my database.
Added creation of 3 accounts, 'editor', 'owner' and 'contributor' (same values for password) during the database seeding, assigning each to a role matching their username on the default created site to simplify testing.
> Add page.unpublish permission

- resources/assets/js/components/PublishModal.vue
See https://trello.com/c/LoBKgsye/292-homepage-not-published-error-message.
This attempts to display the error messages in the API response to the user, assuming that the API responses will have user friendly messages.
> Better not published error

- resources/assets/js/classes/helpers.js
- resources/assets/js/components/PublishModal.vue
- resources/assets/js/components/TopBar.vue
- resources/assets/js/store/modules/site.js
Added a couple of helpers to ensure clickable links for previewing the draft and published versions
of pages are correct.
> Fix Draft and Published Preview URL links

- resources/assets/js/classes/helpers.js
This fixes the issue where previewing published homepages resulted in 404s due to trailing slashes on urls which test server is currently not appreciating.
> Remove trailing slashes from preview urls.

- app/Models/APICommands/UpdateContent.php
Adding in a missed validation message for the case where there are no blocks in a section that isn't optional
> Add missed validation message

- app/Http/Controllers/Api/v1/LayoutController.php
- resources/assets/js/components/CreatePageModal.vue
- resources/assets/js/components/TopBar.vue
- resources/assets/js/store/modules/site.js
- resources/assets/js/views/App.vue
- resources/assets/js/views/SiteList.vue
The create site and add page dialogues used different lists of layouts.
This PR uses loads a list of layouts into the state using the API and then uses this list for both of these dialogues, and also displays the layout version in the list of choices.
> Use layouts list as returned by the API for populating layout choices.

- app/Http/Controllers/Api/v1/SiteController.php
- app/Models/APICommands/AddPage.php
- app/Models/APICommands/AddsPagesTrait.php
- app/Models/APICommands/CreateSite.php
- app/Models/Definitions/BaseDefinition.php
- app/Models/Definitions/SiteDefinition.php
- app/Models/LocalAPIClient.php
- app/Models/Site.php
- app/Policies/Definitions/SiteDefinitionPolicy.php
- app/Providers/AppServiceProvider.php
- app/Providers/AuthServiceProvider.php
- database/migrations/2017_11_30_145150_add_site_template_name_and_version_to_sites.php
- database/seeds/DatabaseSeeder.php
- resources/assets/js/components/TopBar.vue
- resources/assets/js/console/commands/validate.js
- resources/assets/js/store/modules/site.js
- resources/assets/js/test/schemas/site.spec.json
- resources/assets/js/views/SiteList.vue
- routes/api.php
- tests/Support/Astro.postman_collection.json
- tests/Support/Fixtures/definitions/sites/one-page-site/v1/definition.json
- tests/Unit/Models/APICommands/AddPageTest.php
- tests/Unit/Models/APICommands/CreateSiteTest.php
- tests/Unit/Models/APICommands/DeletePageTest.php
- tests/Unit/Models/APICommands/MovePageTest.php
- tests/Unit/Models/APICommands/UpdateSiteTest.php
- tests/Unit/Models/LocalAPIClientTest.php
- tests/Unit/Models/PageTest.php
This PR adds site templates.
When creating a site users now select a site template instead of a homepage layout template, which defines the standard pages that should be created for the new site (their slug, title, layout and any subpages).
Site templates have their own definitions (similar to layouts, regions and blocks), stored in the definitions folder as:
` /sites/{template-name}/v{version}/definition.json`
A json schema for site definitions has been added, and they are validated (alongside other definitions) using the command:
`yarn run validate`
**This branch requires the https://github.com/unikent/cms-prototype-blocks/tree/feature/site-definitions definitions branch (until that has been merged into epic/templates)**
Still TODO is filtering the list of layouts available to the user …
> WIP - Site definitions (Templates)

- app/Http/Transformers/Api/v1/SiteTransformer.php
- resources/assets/js/components/CreatePageModal.vue
- resources/assets/js/store/modules/page.js
This feature restricts the list of available layouts when creating a new page in the editor.
It restricts them to those which are listed in the site's definition availableLayouts array.
If the site definition does not have the availableLayouts attribute, then all layouts will be available.
This PR adds a couple of getters to store/modules/page.js to get the site's definition and adds the layout list filtering code to CreatePageModal.
> Restrict available layouts in add page dialog to those that are allowed in the current site.

- resources/assets/js/classes/helpers.js
- resources/assets/js/components/TopBar.vue
- resources/assets/js/views/MenuEditor.vue
We were trying to merge everything in before the end of the day but jumped the gun before I'd updated the PR :D
TopBar now displays the site title correctly, even if there is only one site available to a user.
Two very minor changes to placeholders in the menu editor component and replaced a commented out bit of code in helpers with a more helpful TODO.
> Quick fixes for a couple of bits that slipped by in the last PR.

- resources/assets/js/store/modules/site.js
This was due to the slug being set before it should have been (the previous slug was needed first to grab the parent's path).
> Fix a bug where the paths in the page listing weren't set correctly.

- app/Models/APICommands/AddsPagesTrait.php
- app/Models/APICommands/UpdateContent.php
- app/Models/Definitions/Layout.php
- app/Models/Definitions/Region.php
- app/Models/Page.php
Fixes #212
Baking pages worked by creating the page data structure from the blocks in the database for that page.
This meant that any optional sections with no blocks currently configured would not be present in the baked data.
This fix first creates an empty (blockless) page data structure containing all regions and sections for the page's layout and then adds all the blocks from the database for the page to this structure.
> Baking pages includes all sections and regions for the page layout. 

- resources/assets/js/store/modules/page.js
Fixes #213 
In the site editor, the UI doesn't display validation errors in blocks when a page has been loaded. And so when you try to save the page, it tells you there are errors but gives no indication of where it is.
This fix restores previously existing functionality which was probably disabled when adding sections.
> Log and notify user of block errors on page load.

- resources/assets/js/components/PageListItem.vue
- resources/assets/js/components/ResizeShim.vue
- resources/assets/js/components/Toolbar.vue
- resources/assets/js/components/TopBar.vue
- resources/assets/js/store/modules/page.js
- resources/assets/js/views/Preview.vue
- resources/assets/sass/_element-ui.scss
This validates a page's layout by ensuring it has the correct regions, sections and blocks. If there is an issue with the page, its blocks will not be rendered, and an error is showns.
Fixes: https://github.com/unikent/astro/issues/168
> Validate page layout when the editor is loaded

- resources/assets/js/classes/helpers.js
Fixes #198 regression for now.
Disabling all buttons and forms in layouts had the side-effect that our empty section
component's add block button was also disabled.
> Do not disable buttons in editor if they have class el-button

- resources/assets/js/components/CreatePageModal.vue
- resources/assets/js/store/modules/site.js
Fixes #227 by using a computed property for the page title in the CreatePageModal with a setter
that checks if the user has manually edited the slug and if not sets the slug to the slugified title.
The slug input now reacts to the change event instead of the focus event to determine whether or not
the user has started editing it manually.
Also minor refactor on the createForm data model to make it saner.
> CreatePageModal generates slug automatically from page title unless user edits slug.

- app/Validation/Brokers/DefinitionBroker.php
- app/Validation/Brokers/RegionBroker.php
Let DefinitionBroker extend BaseDefinition, so that RegionBroker can use the same constructor.
See https://github.com/unikent/astro/issues/169
> fix DefinitionBroker inheritance

- app/Http/Controllers/Api/v1/MediaController.php
- app/Policies/MediaPolicy.php
- If a user can view a site, then they can view media associated with that site.
- For now if a user has the "ADD_IMAGE" permission they can create media.
I'm pretty keen for us to decide on the correct permissions for media (not just images) and when we get the chance to write some better tests to check it's all working as intended.
> Make sure the media controller performs the correct permission checks
